### ISSUE TITLE
`finally` behavior in `Derived.prototype.value` getter

### ISSUE THREAD

**Issue by chriskrycho** [cafreeman/signalis#2]
I was thinking about how we could make this type safe:

https://github.com/cafreeman/reactiv/blob/37bd8c7125e8add4d945843d61abb1d40c914862/src/derived.ts#L39-L42

And the key is the relationship between `prevTags` and `prevResult`, managed here:

https://github.com/cafreeman/reactiv/blob/37bd8c7125e8add4d945843d61abb1d40c914862/src/derived.ts#L55-L90

Mulling on this, I had a few questions:

1. *Should* this be updating the `prevTags` if computing an updated `result` fails?
2. Along the same lines, should it be doing the updates for effects in the case of a failed `computeFn()`?

The questions aren't intended to imply a negative, to be clear—they’re an expression of a relatively ill-formed mental model on my part. Is the model that even if computation fails at the level of *throws an error*, we should update the dependencies? The "right" semantics here aren't at all obvious to me, and I *think* I see why you landed on what you did here, but I’d love to understand more—especially in pursuit of figuring out whether we can make that `// SAFETY` claim actually hold… because right now I think it’s actually a lie. 😂 

(At a meta-level, part of what makes this tricky is that we don’t have any good way to require that functions be non-fallible in JS. My kingdom for `Option` and `Result` instead of exceptions. 😩)

**Comment by cafreeman** [comment]
Welp it looks like I completely missed this for..............months :(

Sorry about that. That said, given the months of conversations we've had about Signalis since, and the fact that it doesn't use tags anymore, I'm going to go ahead and close this one 😛
